# Docker Environment Configuration
version: '3.8'

services:
  # Only databases for local development
  postgres-local:
    image: postgres:15-alpine
    container_name: my_finance_postgres_local
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    networks:
      - local_network

  mongodb-local:
    image: mongo:7.0
    container_name: my_finance_mongodb_local
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: account_db
    ports:
      - "27018:27017"  # Different port to avoid conflicts
    volumes:
      - mongodb_local_data:/data/db
    networks:
      - local_network

  mysql-local:
    image: mysql:8.0
    container_name: my_finance_mysql_local
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gateway_db
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql123
    ports:
      - "3307:3306"  # Different port to avoid conflicts
    volumes:
      - mysql_local_data:/var/lib/mysql
    networks:
      - local_network

  # UI Tools for local development
  pgadmin-local:
    image: dpage/pgadmin4:latest
    container_name: my_finance_pgadmin_local
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@myfinance.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"
    volumes:
      - pgadmin_local_data:/var/lib/pgadmin
    depends_on:
      - postgres-local
    networks:
      - local_network

  mongo-express-local:
    image: mongo-express:latest
    container_name: my_finance_mongo_express_local
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin123@mongodb-local:27017/
    ports:
      - "8082:8081"
    depends_on:
      - mongodb-local
    networks:
      - local_network

  phpmyadmin-local:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my_finance_phpmyadmin_local
    environment:
      PMA_HOST: mysql-local
      PMA_PORT: 3306
      PMA_USER: mysql_user
      PMA_PASSWORD: mysql123
    ports:
      - "8083:80"
    depends_on:
      - mysql-local
    networks:
      - local_network

volumes:
  postgres_local_data:
  mongodb_local_data:
  mysql_local_data:
  pgadmin_local_data:

networks:
  local_network:
    driver: bridge